[phases.setup]
nixPkgs = [
  "ffmpeg",                     # Já incluído, mas certifique-se de que está corretamente configurado
  "libopus",                    # Adicionando o libopus
  "python311",                   # A versão do Python
  "python311Packages.pynacl",    # Necessário para o Discord
  "python311Packages.discordpy" # Instala o discord.py com suporte para voz
]

[phases.start]
cmd = "python3 bot.py"
