[phases.setup]
nixPkgs = [
  "ffmpeg",                     # Já incluído
  "libopus",                    # Adicionando libopus
  "python311",                   # Python 3.11
  "python311Packages.pynacl",    # Necessário para Discord
  "python311Packages.discordpy" # Instala o discord.py
]

[phases.install]
cmd = "apt-get update && apt-get install -y libopus-dev" # Instalar libopus

[phases.start]
cmd = "python3 bot.py"
